name: Just Build

env:
  main_project_module: app

on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - name: Build
        run: |
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          echo ${{ secrets.STORE }} | base64 -d > upload.jks
          echo ${{ secrets.LOCAL }} | base64 -d > local.properties
          chmod +x ./gradlew;
          ./gradlew clean assembleRelease --stacktrace
          rm upload.jks local.properties
          
      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}
    
      - name: Upload (GitHub)
        uses: actions/upload-artifact@v7
        with:
          name: airplay-apk-${{github.sha}}
          path: |
            app/build/outputs/apk/release/app-release-unsigned-signed.apk
          if-no-files-found: error

  build-aab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - name: Build
        run: |
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          echo ${{ secrets.STORE }} | base64 -d > upload.jks
          echo ${{ secrets.LOCAL }} | base64 -d > local.properties
          chmod +x ./gradlew;
          ./gradlew clean bundleRelease --stacktrace
          rm upload.jks local.properties

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Upload (GitHub)
        uses: actions/upload-artifact@v7
        with:
          name: airplay-aab-${{github.sha}}
          path: |
            app/build/outputs/bundle/release/app-release.aab
          if-no-files-found: error
